Rails:
    Enabled: true

# Commonly used screens these days easily fit more than 80 characters.
Metrics/LineLength:
  Max: 100

# Mixing the hash styles looks just silly.
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

# Don't require nested classes. Use Module::Class instead
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
