#!/bin/bash

set -euo pipefail

dir=${1:-$(dirname "$0")}

if [[ $# -gt 1 || ! -d $dir ]]; then
  printf "Usage: %s [directory]\n" "${0##*/}"
  printf "Run install under PERSONAL directory if it exists.\n"
  printf "Stow directories to $HOME\n"
  printf "Run stow on all directories under given directory\n"
  printf "Else, run stow on all directories which are siblings to this file\n"
  printf "\nDirectories named Z-* and .* are excluded.\n"
  exit 1
fi

cd "$dir"

# Link personal stow directories to main directory
if [[ -f PERSONAL/install ]]; then
  PERSONAL/install
fi

find -L . -maxdepth 1 -type d ! \( -name '.*' -o -name 'Z-*' \) -printf '%P\0' | xargs -t0 --max-args=1 --no-run-if-empty -- stow -v --target="$HOME"
