# ~/.zshenv - this file will always be sourced, unless:  zsh -f  or  zsh --no-rcs
# Used for setting the user's environment variables.
# It should not contain commands that produce output or assume the shell is attached to a tty.

#
# Startup files:
#
# /etc/zshenv (Arch: /etc/zsh/zshenv)
#  - Is sourced prior to .zshenv, and CANNOT be skipped, even with zsh -f or -o no_rcs
#
# If option GLOBAL_RCS is unset in any of the files, no global configuration files (/etc/zsh/*) will be read after that file.
# If option RCS is unset in any of the files, no configuration files will be read after that file.
#
#  If login shell, the following are read after this file:
#  /etc/zprofile (Arch: /etc/zsh/zprofile)
#  - Only for login shells
#  - At 2025-09-17, contained only:   emulate sh -c 'source /etc/profile'
#
# /etc/profile  (sourced from above)
# - Sources /etc/profile.d/*.sh
#
# $ZDOTDIR/.zprofile
#
# If the shell is interactive, then /etc/zsh/zshrc, and then $ZDOTDIR/.zshrc
#
# Finally, if a login shell, /etc/zsh/zlogin and $ZDOTDIR/.zlogin are read.
#
# When a login shell exits (execept via exec), $ZDOTDIR/.zlogout then /etc/zlogout are read.

# Note: ~/.profile is NOT sourced by default Zsh startup.

# If $ZDOTDIR is not set, $HOME is used instead.
# Dotfiles has:  .zshenv -> .config/zsh/zshenv
export ZDOTDIR=$HOME/.config/zsh

#
# XDG vars should probably be setup from here.
# Split check from setup?
