#!/bin/sh

# Debug functions
# Intended to be optionally sourced when debugging non-interactive shells

# TODO: rename me cmd_to_file?
debug_file() {
  if [ -z "$_debug_file" ]; then
    _debug_file=/tmp/${SHELL_NAME}-$$
    touch "$_debug_file"
    echo "$SHELL_NAME debugging to: $_debug_file" >&2
  fi
  "$@" >> "$_debug_file"
  # echo "$@" ">>" /tmp/$SHELL_NAME-$$
}
