#!/bin/sh
# Interactive shell commands

if [ -n "$_already_sourcing_interactive" ]; then return
else _already_sourcing_interactive=true; fi

# For non-login shells: source env if not yet sourced
if [ -z "$_shell_rc_dir" ]; then
  _shell_rc_dir=${_shell_rc_dir:=${XDG_CONFIG_HOME:=$HOME/.config}/shell}
  . "$_shell_rc_dir"/env
fi
debug_file echo "Reading interactive"

. "${_shell_rc_dir}"/functions-interactive

unset _already_sourcing_interactive
unset _shell_rc_dir
debug_file echo "DONE reading interactive"
