#!/bin/bash #for-shellcheck
# This file gets sourced from .bashrc

# shellcheck disable=SC2142  # Allow fancy pants aliases with positional parameters
# Issue: SC2142 occurs when parameters are used in a function #1263
# https://github.com/koalaman/shellcheck/issues/1263


# Alias colourify to '' if grc doesn't exist
command -v grc > /dev/null || alias colourify=''

# ls aliases
# LS_BLOCK_SIZE = Separate thousands with ','
# https://www.gnu.org/software/coreutils/manual/html_node/Block-size.html
# -C = list entries by columns
# -F, --classify = append indicator (one of */=>@|) to entries
alias ls="colourify ls -CF --block-size=\\'1 --color=always --quoting-style=shell-escape"  #'"
alias la='ls -A'       # Almost all - no . and ..
alias lal='ls -la'
alias ll='ls -l'
alias lsd='ls -dla * --color=always | grep "^d" --color=never'   # non-hidden directories
alias lsdd='ls -Al --color=always | grep --color=never ^d'   # directories including hidden
alias lal='ls -la'
alias l.='ls -d .[^.]?*' # Hidden files except . and .. (current directory only)

alias -- -='cd -' # go to previous dir
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# One letter aliases
alias g='git'
alias h='history'
alias j='jobs'
alias l='ll'  # l^J for ultimate laziness
alias q='ls'  # mnemonic: q = query
alias r='rake'
alias s='git s'

# Two letters
alias ft='faketty '  # space at end allows next word to be alias-expanded
alias gh='git logda' # Git History
alias jc='journalctl'
alias sc='sudo systemctl'

alias scu='systemctl --user'

# Currently done as function
# https://stackoverflow.com/a/34071958/5353461
# alias sbin='export PATH=$(npm bin):$PATH'

# Configuration of base command
alias ag='ag --color'
alias aga='ag --all-types --hidden'
alias cal='cal -3' # show 3 months by default
alias cp='cp -i --reflink=auto --sparse=always'
alias Cp='command cp --reflink=auto --sparse=always'  # Allow overwrite
alias cuc='cucumber'
alias df="colourify df --block-size=\\'1K"  #'"
alias df,='colourify df'
alias diff='diff --color=auto'
alias grep='GREP_COLOR="1;33;40" LANG=C grep --color=auto'
alias home='git --git-dir=$HOME/.githome --work-tree=$HOME'
alias lesc='less-compressed-wrapper'
alias mv='mv -i'
alias Mv='command mv'  # Allow overwrite
alias nixnote2='LD_PRELOAD=libcurl.so.3 nixnote2 &'
alias rsync='rsync --sparse'
alias rm='rm -I'  # Prompt on -r or >3 files
alias Rm='command rm'
alias setvars='(set -o posix; set)'
alias vimpager='$XDG_DATA_HOME/vim/bundle/vimpager/vimpager'

# Have pacmatic wrap aurman/pakku wrap powerpill wrap pacman
# https://unix.stackexchange.com/a/384102/143394
alias pac=aurman
# pacmatic needs to be run as root: https://github.com/keenerd/pacmatic/issues/35
# alias pacmatic='export PYTHONPATH=/usr/lib/python3.6/site-packages; sudo --preserve-env=pacman_program,PYTHON_PATH /usr/bin/pacmatic'
alias pacmatic='PYTHONPATH=/usr/lib/python3.6/site-packages sudo --preserve-env=pacman_program,PYTHON_PATH /usr/bin/pacmatic'
# Downgrade permissions as AUR helpers expect to be run as a non-root user. $UID is read-only in {ba,z}sh.
alias aurman=' pacman_program="sudo -u #$UID /usr/bin/aurman" pacmatic'
alias aurmano='pacman_program="sudo -u #$UID /usr/bin/aurman --optimistic_versioning" pacmatic'
alias pakku='  pacman_program="sudo -u #$UID /usr/bin/pakku" pacmatic'

# tmux / tmuxinator
alias tmux='TERM=xterm-256color tmux -f "$XDG_CONFIG_HOME"/tmux/tmux.conf'
alias tmuxinator='TERM=xterm-256color tmuxinator'
alias mux='TERM=xterm-256color tmuxinator'

# head & tail
alias head='head -n $((${LINES:-12}-2))' # as many as possible without scrolling
alias tail='tail -n $((${LINES:-12}-2)) --sleep-interval=0.2' # 200ms

# Clipboard
alias pbcopy='xclip -selection clipboard -in'
alias pbpaste='xclip -selection clipboard -out'

# rsync
alias droidsync='f(){ rsync "$@" --no-p --no-o --no-g --rsync-path="su root rsync";};f'
# FAT stores to two-second accuracy, NTFS 100 nanoseconds
# https://corengen.wordpress.com/2010/03/22/comparing-file-timestamps-on-ntfs-and-fat32/
alias fatrsync='f(){ rsync "$@" --modify-window=2 --no-p --no-o --no-g;};f'
alias rsyncmv='rsync -a --remove-source-files'

# pygmentize
alias pcat='pygmentize -f terminal256 -O style=monokai -g'
alias pless='f(){ pygmentize -f terminal256 -O style=monokai -g "$@" | less -L; };f'


##
## Begin bash only
##
if [[ $BASH_VERSION ]]; then

  alias as_bash=''  # zshrc has the zsh counterpart

  # Completions for aliases
  # https://brbsix.github.io/2015/11/23/perform-tab-completion-for-aliases-in-bash/
  # https://unix.stackexchange.com/questions/4219/how-do-i-get-bash-completion-for-command-aliases
  # General format: complete -o bashdefault -o default -o nospace -F _git g
  _completion_loader systemctl; complete -o bashdefault -o default -o nospace -F _systemctl sc

  # Allow completion for git aliases defined above
  # See https://github.com/cykerway/complete-alias for a generic solution
  if is_function __git_complete; then
    __git_complete g __git_main
    __git_complete home __git_main
    __git_complete s _git_status
  fi
fi

##
## End bash only
##

[[ $BASH_VERSION ]] && return

##
## zsh only from here until EOF
##

[[ $ZSH_VERSION ]] && {
  alias -g ...='../..'
  alias -g ....='../../..'
  alias -g .....='../../../..'
  alias -g B='  | bust'  # Head
  alias -g BA='|& bust'
  alias -g C='| wc -l'
  alias -g DN='    /dev/null'
  alias -g DNO=' > /dev/null'
  alias -g DNA='&> /dev/null'
  alias -g DNE='2> /dev/null'
  alias -g H='  | head'  # Head
  alias -g HA='|& head'
  alias -g G=' | grep -E'  # egrep is deprecated
  alias -g GA='|& grep -E'
  alias -g GE='|& grep -E' XXXXXXXX
  alias -g L="  | less"
  alias -g LA=" |& less"
  alias -g LS=" | less -S"  # -S or --chop-long-lines
  alias -g LSA="|& less -S"  # -S or --chop-long-lines
  alias -g M='| more'
  alias -g P='|'
  alias -g R='| rear'
  alias -g SU='| sort'
  alias -g T='| tail'
  alias -g US='| sort -u'
  alias -g U='| uniq'
  alias -g X='| xargs'

# From zsh-lovers not yet checked
  alias -g CA="2>&1 | cat -A"
  alias -g D="DISPLAY=:0.0"
  alias -g ED="export DISPLAY=:0.0"
  alias -g ELS='|& less -S'
  alias -g ETL='|& tail -20'
  alias -g ET='|& tail'
  alias -g F=' | fmt -'
  alias -g Sk="*~(*.bz2|*.gz|*.tgz|*.zip|*.z)"
  alias -g LL="2>&1 | less"
  alias -g LS='| less -S'
  alias -g MM='| most'
  alias -g NE="2> /dev/null"
  alias -g NS='| sort -n'
  alias -g RNS='| sort -nr'
  alias -g VM=/var/log/messages
  alias -g X0G='| xargs -0 egrep'
  alias -g X0='| xargs -0'
  alias -g XG='| xargs egrep'
}
