#!/bin/bash #for-shellcheck
# This file gets sourced from .bashrc

# ls aliases
# https://www.gnu.org/software/coreutils/manual/html_node/Block-size.html
alias ls="BLOCK_SIZE=\'1 ls --color=auto" #enable thousands grouping and colour
alias l="ls -bCF"         # escape non printable || columns || decorated
alias la="ls -CAFb"       # Almost all - no . and ..
alias ld="ls -dlaFb */"   # no-dereference symlinks, directory entry instead of contents
alias ll="ls -laFb"
alias ls.="ls -dbCF .[^.]?*" # Hidden files except . and .. (currend directory only)
alias lsd="ls -Abl | grep --color=never ^d"   # list only directories

alias -- -="cd -" # go to previous dir
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# One letter aliases
alias g="git"
alias h="history"
alias j="jobs"
alias r="rake"
alias s="git s"

# Two letters
alias gh="git logda" # Git History

# Configuration of base command
alias ag="ag --color"
alias cal='cal -3' # show 3 months by default
alias cp='cp --reflink=auto'
alias cuc=cucumber
alias diff='diff --color=auto'
alias grep='GREP_COLOR="1;33;40" LANG=C grep --color=auto'
alias home="git --git-dir=$HOME/.githome --work-tree=$HOME"
alias open='&>>~/.xsession-errors xdg-open'
alias nixnote2='LD_PRELOAD=libcurl.so.3 nixnote2 &'
alias tmux='TERM=xterm-256color tmux'
alias tmuxinator='TERM=xterm-256color tmuxinator'

alias head='head -n $((${LINES:-12}-2))' # as many as possible without scrolling
alias tail='tail -n $((${LINES:-12}-2)) -s.1' # Likewise, also more responsive -f
