#!/bin/bash
# ^ keep shell-check happy

# XDG - set defaults as they may not be set (eg Ubuntu 14.04 LTS)
# See https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
# and https://wiki.archlinux.org/index.php/XDG_Base_Directory_support
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
if [ ! -w ${XDG_RUNTIME_DIR:="/run/user/$UID"} ]; then
    echo "\$XDG_RUNTIME_DIR ($XDG_RUNTIME_DIR) not writable. Setting to /tmp." >&2
    XDG_RUNTIME_DIR=/tmp
fi
export XDG_RUNTIME_DIR

# Export the XDG user directories
if [ -f "$XDG_CONFIG_HOME/user-dirs.dirs" ]; then
    . "$XDG_CONFIG_HOME/user-dirs.dirs"
    export XDG_DESKTOP_DIR XDG_DOWNLOAD_DIR XDG_TEMPLATES_DIR XDG_PUBLICSHARE_DIR XDG_DOCUMENTS_DIR XDG_MUSIC_DIR XDG_PICTURES_DIR XDG_VIDEOS_DIR
fi

# Check that only one version of XDG files exist
while read -r file; do
    case "$file" in
        \#*) continue # Allow for commened out files
    esac
    if [ -e "$file" ]; then
        echo "Warning: XDG shadowed file: $file" >&2
    fi
done << XDGFILES
   $HOME/.inputrc
   $HOME/.less
   $HOME/.gnupg
   $HOME/.lesshst
   # X/ICEauth don't listen currently, silence them...
   # $HOME/.Xauthority
   # $HOME/.ICEauthority
   $HOME/.gitconfig
   $HOME/.vim
   $HOME/.viminfo
   $HOME/.npm
   $HOME/.npmrc
   $HOME/.mostrc
XDGFILES

# Tell programs to look for files in $XDG_*
# When adding a file here, ensure it's default location is added
# to the XDGFILES "here" string above
# Config


# Single-line config
export INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"
export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"
export MOST_INITFILE="$XDG_CONFIG_HOME/most/config"

# Begin multi-line config

export LESSKEY="$XDG_CONFIG_HOME/less/keys"
export LESSHISTFILE="$XDG_CACHE_HOME/less/history"

# npm
# see npm config ls -l | grep /
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/config
export NPM_CONFIG_CACHE=$XDG_CACHE_HOME/npm
export NPM_CONFIG_TMP=$XDG_RUNTIME_DIR/npm

# X11
export XAUTHORITY="$XDG_CACHE_HOME/Xauthority"
mkdir -p "$XDG_RUNTIME_DIR/X11"
export ICEAUTHORITY="$XDG_RUNTIME_DIR/X11/ICEauthority"
export XAUTHORITY="$XDG_RUNTIME_DIR/X11/Xauthority"

# vim - Set vimrc and viminfo location before vim startup
export VIMINIT='let $MYVIMRC="'"$XDG_CONFIG_HOME"'/vim/vimrc"|source $MYVIMRC'
