#!/bin/bash
# shellcheck disable=1090
# ^ don't try to check variable-named sourced files
# ^ keep shell-check happy

# XDG - set defaults as they may not be set (eg Ubuntu 14.04 LTS)
# See https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
# and https://wiki.archlinux.org/index.php/XDG_Base_Directory_support
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:=$HOME/.local/share}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:=$HOME/.cache}"

# See http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02 for this "+x" syntax
# Note that quotes are needed should IFS=x and not in [[
if [[ -z ${XDG_RUNTIME_DIR+x} ]]; then
   if [[ ! -w ${XDG_RUNTIME_DIR:="/run/user/$UID"} ]]; then
      echo "\$XDG_RUNTIME_DIR ($XDG_RUNTIME_DIR) not writable. Setting to /tmp." >&2
      XDG_RUNTIME_DIR=/tmp
   fi
fi
export XDG_RUNTIME_DIR

# Export the XDG user directories
if [ -f "$XDG_CONFIG_HOME/user-dirs.dirs" ]; then
    . "$XDG_CONFIG_HOME/user-dirs.dirs"
    export XDG_DESKTOP_DIR XDG_DOWNLOAD_DIR XDG_TEMPLATES_DIR XDG_PUBLICSHARE_DIR XDG_DOCUMENTS_DIR XDG_MUSIC_DIR XDG_PICTURES_DIR XDG_VIDEOS_DIR
fi

# Only warn that symlinks are shadowed on the odd occasion
((RANDOM % 50 == 0)) && _print_links=true

# Check that only one version of files exist
while read -r file; do # HERE doc at end
  case "$file" in
    "") ;&
    \#*) continue # Allow for blank and commened out files
  esac
  if [[ -e $file ]]; then { # bracket for STDERRR
    if [[ -L $file && ! -v _print_links ]]; then continue; fi
    printf "%s" "Warning: XDG shadowed "
    # shellcheck disable=SC2015 # A && B || C is not if-then-else. C may run when A is true. [SC2015]
      [[ -L $file ]] && printf "symlink" || { # symlinks are "both"
        [[ -d $file ]] && printf "directory"
        [[ -f $file ]] && printf "file";
      }
      printf ": %s\n" "$file"
    } >&2
  fi
done << XDGFILES
   $HOME/.inputrc
   $HOME/.less
   $HOME/.gnupg
   $HOME/.lesshst
   # X/ICEauth don't listen currently, silence them...
   # $HOME/.Xauthority
   # $HOME/.ICEauthority
   $HOME/.gitconfig
   $HOME/.npm
   $HOME/.npmrc
   $HOME/.mostrc
   $HOME/.tmux
   $HOME/.tmuxinator
   $HOME/.vim
   $HOME/.viminfo
   $HOME/.vimperator
   $HOME/.wgetrc
XDGFILES
unset _print_links

# Tell programs to look for files in $XDG_*
# When adding a file here, ensure it's default location is added
# to the XDGFILES "here" string above
# Config


# Single-line config
export INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"
export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"
export MOST_INITFILE="$XDG_CONFIG_HOME/most/config"
export WGETRC="$XDG_CONFIG_HOME/wgetrc"

# Begin multi-line config

export LESSKEY="$XDG_CONFIG_HOME/less/keys"
export LESSHISTFILE="$XDG_CACHE_HOME/less/history"

export VIMPERATOR_INIT=":source $XDG_CONFIG_HOME/vimperator/vimperatorrc"
export VIMPERATOR_RUNTIME="$XDG_CONFIG_HOME/vimperator"

# npm
# Check config with:   npm config ls -l | grep / | grep -v '^;'
# More XDG config is inside the config file itself:
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/config

# # Uncommenting breaks Manjaro login
# X11
# export XAUTHORITY="$XDG_CACHE_HOME/Xauthority"
# mkdir -p "$XDG_RUNTIME_DIR/X11"
# export ICEAUTHORITY="$XDG_RUNTIME_DIR/X11/ICEauthority"
# export XAUTHORITY="$XDG_RUNTIME_DIR/X11/Xauthority"

# vim - Set vimrc and viminfo location before vim startup
# shellcheck disable=2016
export VIMINIT='let $MYVIMRC="'"$XDG_CONFIG_HOME"'/vim/vimrc"|source $MYVIMRC'
